on: [push, pull_request]

name: libp2p-webrtc

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - name: setup rustup
      run: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain none -y

    - name: cargo fmt
      run: cargo fmt --all -- --check

    - name: cargo clippy
      run: cargo clippy --workspace --examples --tests --all-features -- -D warnings
    
    - name: cargo build
      run: cargo build --locked

    - name: cargo test
      run: RUST_LOG=debug cargo test --all-features
